baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'snowball'
Theme = 'snowball'

[menu]
  [[menu.main]]
    name = "Content"
    url = "/content/"
    weight = 1

  [[menu.main]]
    name = "Document"
    url = "/document/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3