baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'snowball'
Theme = 'snowball'
paginate = 4

[author]
  name = "Wojciech Rzepka"

[params]
  author = "Wojciech Rzepka"
  description = 'Documentation template in Hugo'
  metaKeywords = ["documentation", "minimal", "dark", "hugo", "snowball"]

[menu]
  [[menu.main]]
    name = "Sample content"
    url = "/content/"
    weight = 1

  [[menu.main]]
    name = "Document"
    url = "/document/"
    weight = 2

  [[menu.main]]
    name = "Guide"
    url = "/guide/"
    weight = 3

  [[menu.main]]
  name = "Documents"
  url = "/document/"
  weight = 4