baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'snowball'
Theme = 'snowball'
paginate = 4
enableEmoji = true
enableRobotsTXT = true

[author]
  name = "Wojciech Rzepka"

[params]
  author = "Wojciech Rzepka"
  description = 'Documentation template in Hugo'
  metaKeywords = ["documentation", "minimal", "dark", "hugo", "snowball"]

[menu]
  [[menu.main]]
    name = "Guide"
    url = "/guide/"
    weight = 1

  [[menu.main]]
    name = "Stylings"
    url = "/content/"
    weight = 2

  [[menu.main]]
    name = "Articles"
    url = "/article/"
    weight = 3